#!/usr/bin/env python3
"""
Test single prompt with the Sage Intacct query
"""

import asyncio
from datetime import datetime
from deep_research import research_agent
from advanced_research import advanced_researcher

def test_prompt1():
    """Test testprompt1"""
    query = "Sage Intacct wants to focus on selling to SMB & Mid sized Healthcare companies. What is the competition that we could come across in this space"
    
    print("🧪 Testing testprompt1 (Basic Research)...")
    print(f"Query: {query}")
    print("=" * 60)
    
    try:
        result = research_agent.generate_research_report(query, "testprompt1")
        
        # Save to file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"testprompt1_result_{timestamp}.md"
        
        content = f"""# testprompt1 Result - Sage Intacct Healthcare Competition

**Query:** {query}  
**Test Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Model:** {result.get('model', 'Unknown')}  
**Sources Used:** {result.get('sources_used', 'Unknown')}  

---

{result.get('content', 'No content available')}

---

*Generated by PMM Research Agent - testprompt1*
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ testprompt1 completed! Saved to: {filename}")
        return filename
        
    except Exception as e:
        print(f"❌ testprompt1 failed: {e}")
        return None

def test_prompt3():
    """Test testprompt3"""
    query = "Sage Intacct wants to focus on selling to SMB & Mid sized Healthcare companies. What is the competition that we could come across in this space"
    
    print("🧪 Testing testprompt3 (Advanced 3-Stage Research)...")
    print(f"Query: {query}")
    print("=" * 60)
    
    try:
        result = asyncio.run(advanced_researcher.conduct_advanced_research(query, "testprompt3"))
        
        # Save to file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"testprompt3_result_{timestamp}.md"
        
        content = f"""# testprompt3 Result - Sage Intacct Healthcare Competition

**Query:** {query}  
**Test Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Model:** {result.get('model', 'Unknown')}  
**Sources Used:** {result.get('sub_questions_researched', result.get('total_sources', 'Unknown'))}  

---

{result.get('content', 'No content available')}

---

*Generated by PMM Research Agent - testprompt3*
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ testprompt3 completed! Saved to: {filename}")
        return filename
        
    except Exception as e:
        print(f"❌ testprompt3 failed: {e}")
        return None

def test_prompt4():
    """Test testprompt4"""
    query = "Sage Intacct wants to focus on selling to SMB & Mid sized Healthcare companies. What is the competition that we could come across in this space"
    
    print("🧪 Testing testprompt4 (Data-Driven Research)...")
    print(f"Query: {query}")
    print("=" * 60)
    
    try:
        result = research_agent.generate_research_report(query, "testprompt4")
        
        # Save to file
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"testprompt4_result_{timestamp}.md"
        
        content = f"""# testprompt4 Result - Sage Intacct Healthcare Competition

**Query:** {query}  
**Test Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}  
**Model:** {result.get('model', 'Unknown')}  
**Sources Used:** {result.get('total_sources', 'Unknown')}  

---

{result.get('content', 'No content available')}

---

*Generated by PMM Research Agent - testprompt4*
"""
        
        with open(filename, 'w', encoding='utf-8') as f:
            f.write(content)
        
        print(f"✅ testprompt4 completed! Saved to: {filename}")
        return filename
        
    except Exception as e:
        print(f"❌ testprompt4 failed: {e}")
        return None

if __name__ == "__main__":
    import sys
    
    if len(sys.argv) > 1:
        prompt = sys.argv[1]
        if prompt == "1":
            test_prompt1()
        elif prompt == "3":
            test_prompt3()
        elif prompt == "4":
            test_prompt4()
        else:
            print("Usage: python test_single_prompt.py [1|3|4]")
    else:
        print("Usage: python test_single_prompt.py [1|3|4]")
        print("Example: python test_single_prompt.py 1") 